### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by dbohdan** [olsonpm/sqlite-to-rest#5]
`package.json` says the license is ISC, but there is no license file in the repository.

**Comment by olsonpm** [comment]
I'll add it.  Thanks much

**Comment by olsonpm** [comment]
every time I revisit looking at licenses it makes me angry how ridiculous the landscape is and each time I fall back to the wtfpl because it at least clearly communicates what I intend.  If someone needs this in a more professional setting or to be compatible with OSI then they can fork.
