### ISSUE TITLE
Add repository topic "automatic-api"

### ISSUE THREAD

**Issue by dbohdan** [olsonpm/sqlite-to-rest#6]
Could you add the topic (tag) "[automatic-api](https://github.com/topics/automatic-api)" to your repository? There still isn't an established term for software that does this kind of thing. It will be easier to discover if there is a standard GitHub topic. Many projects have already added it.

**Comment by olsonpm** [comment]
Will do, just woke up and I'd like to read about topic tags before I do it just so I understand.  Thanks for the suggestion.

**Comment by olsonpm** [comment]
Done - thanks again
